### ISSUE TITLE
Features for `1.0`

### ISSUE THREAD

**Issue by sgammon** [buildless/plugin-gradle#65]
Once we're out of beta, the goal is to have a more complete plugin experience, with some extra best-practices support provided by some open source plugins, as well as improvements made to the Buildless plugin itself.

In each case, we'll need to check/enclose licenses, contact authors (as needed), and otherwise obtain proper permission to embed this code or seek alternatives.

## Plugins we may want to bundle

- [ ] [**Gradle Doctor**][1]: This plugin is fantastic for catching major mistakes in a Gradle build, many of which can hurt cache performance. In addition to these checks, the plugin also measures cache efficiency and offers recommendations about targets that should be withheld from the cache.

- [ ] [**Build time tracker**][2]: This plugin offers a summary at the end of a build, showing the set of tasks which took the longest. It would be especially cool to extend this plugin with color support and with embedded time-savings charts from use of Buildless.

- [ ] [**Android cache fix**][3]: This plugin applies fixes to Android builds which improve/fix caching. The plugin comes directly from the Gradle team.

- [ ] [**Common user data**][4]: This plugin is offered by the Gradle team for a downstream team to customize; we may want to offer our own Buildless-enhanced alternative, or otherwise provide an easy path for use (if we don't bundle).

## Functionality we want to add

- [ ] **Transport**: Enhanced HTTP2 transport for communicating with the cache.

- [ ] **Pkgst**: Extensions and other DSL for easily activating Pckgst support.

- [ ] **Local env**: Smarter local env, with support for `CACHE_ENDPOINT` overrides, and suppressing local or remote caching via other env vars.

[1]: https://github.com/runningcode/gradle-doctor
[2]: https://github.com/asarkar/build-time-tracker
[3]: https://github.com/gradle/android-cache-fix-gradle-plugin
[4]: https://github.com/gradle/common-custom-user-data-gradle-plugin
